### ISSUE TITLE
YCB Dataset Infos

### ISSUE THREAD

**Issue by jako-dev** [ethnhe/PVN3D#21]
Hi,
i'm trying to train pvn3d on my own synthetic dataset, which i created with NDDS by Nvidia (Unreal Engine).
Could you give me some further information about the:
-corners.txt and farthest.txt in /pvn3d/datasets/ycb/object_kps/ [https://github.com/ethnhe/PVN3D/tree/master/pvn3d/datasets/ycb/ycb_object_kps/002_master_chef_can](url) and
-radius.txt in /pvn3d/datasets/ycb/dataset_config [https://github.com/ethnhe/PVN3D/blob/master/pvn3d/datasets/ycb/dataset_config/radius.txt](url)

Thank you so much.

**Comment by ethnhe** [comment]
- The corners.txt is the bounding box corners. It can be obtained by getting the min_x, max_x, min_y, max_y ... of all mesh points.
- The radius can be obtained by half the diagonal distance of the 3D bounding box.
- The farthest.txt contains keypoint selected from all mesh points with the Farthest Point Sampling (FPS) algorithm.

**Comment by jako-dev** [comment]
Thank you very much for your fast reply.

**Comment by Michael187-ctrl** [comment]
Hey Jako, can you please describe a little bit further how to create a dataset on your own for me?

**Comment by jako-dev** [comment]
I generate synthetic data with NDDS (Unreal Engine Plugin) by Nvidia (https://github.com/NVIDIA/Dataset_Synthesizer).

Follow their instructions on how to use it.
You need to have a mesh (.fbx/.obj etc.) file of your object. After you set up your Project in Unreal Engine, you can generate unlimited amounts of synthetic data (incl. instance seg., class seg., depth, rgb...) fully annotated with 3d bounding box, pose transform matrix, 2d bounding box, 2d/3d centroid, camera intrinsics matrix and some more annotations.

If you want to use it with pvn3d, you need to do some formatting and adapt the train/dataset scripts to this (which im doing right now).

**Comment by Michael187-ctrl** [comment]
Thank you for your answer :)Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: jako-dev <notifications@github.com> Datum: 05.06.20  09:43  (GMT+01:00) An: ethnhe/PVN3D <PVN3D@noreply.github.com> Cc: Michael187-ctrl <michael.weigend187@gmail.com>, Comment <comment@noreply.github.com> Betreff: Re: [ethnhe/PVN3D] YCB Dataset Infos (#21) 
I generate synthetic data with NDDS (Unreal Engine Plugin) by Nvidia (https://github.com/NVIDIA/Dataset_Synthesizer).
Follow their instructions on how to use it.
You need to have a mesh (.fbx/.obj etc.) file of your object. After you set up your Project in Unreal Engine, you can generate unlimited amounts of synthetic data (incl. instance seg., class seg., depth, rgb...) fully annotated with 3d bounding box, pose transform matrix, 2d bounding box, 2d/3d centroid, camera intrinsics matrix and some more annotations.
If you want to use it with pvn3d, you need to do some formatting and adapt the train/dataset scripts to this (which im doing right now).

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ethnhe/PVN3D/issues/21#issuecomment-639315222",
"url": "https://github.com/ethnhe/PVN3D/issues/21#issuecomment-639315222",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Michael187-ctrl** [comment]
Hey jako-dev ,
did you already have success with adapting the train and dataset scripts with good results on your own Dataset?

**Comment by jako-dev** [comment]
Hi, sorry for the late reply. Unfortunately not yet. I‘m having trouble to fully understand a few lines of the code, but i think i‘m close to be able to train. I wont be able to work further on it until next monday.

**Comment by Michael187-ctrl** [comment]
No problem! I would be really grateful if you could let me know if it worked and how. The original way via raster triangle and with use of https://github.com/zju3dv/pvnet-rendering seems not very pleasing , because everywhere the ycb and linemod classes are hardcoded

**Comment by jako-dev** [comment]
Hi @Michael187-ctrl,
i am able to train on my custom dataset now. I still need to validate if training is sucessful. If so, i will let you know.

**Comment by Michael187-ctrl** [comment]
Hey @jako-dev , that sounds good. Thanks for your nice distribution

**Comment by Ixion46** [comment]
Hey @ethnhe , you wrote that the farthest.txt contains keypoints selected from the mesh points of an object. But why are the result points not in the mesh file?

**Comment by KatharinaSchmidt** [comment]
Hello,
I would also be interested in training PVN3D with my own dataset, which I generated with NDDS. It would be very helpfullfor me (and maybe some others too) if you could share your modifications in the code. 

Thanks, 
Katharina

**Comment by jako-dev** [comment]
@KatharinaSchmidt I'm planning to do that but i still have issues.

**Comment by Michael187-ctrl** [comment]
@jako-dev can you please upload your changes to github? Would really appreciate your help
