### ISSUE TITLE
Why Linemod need many weights but ycb only need one?

### ISSUE THREAD

**Issue by EasonEdison** [ethnhe/PVN3D#3]
as title, looking forward ot  your reply

**Comment by ethnhe** [comment]
Because only ground true mask of one object in a scene is provided in the LineMOD dataset, making it hard to train a single semantic segmentation model for all objects as many objects are unlabeled in a scene. While all objects are labeled with a ground true mask in the YCB-Video dataset. So it's possible to train a single model for all objects.

**Comment by EasonEdison** [comment]
wow！ thank you for your reply
